import { Common } from '@Blocks/Card'

export const slimCard: Parameters<typeof Common>[0][] = [
  {
    bgImg: '/media/posters/1.jpg',
    title: 'Tracing Your Roots Through Food',
    // subtitle: 'Chai Li',
    badges: ['Live', 'Food'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/posters/2.jpg',
    title: 'Mathematical Thinking',
    // subtitle: 'Kevin Sanjaya',
    badges: ['Offline', 'Science & Tech'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/posters/3.jpg',
    title: 'Purposeful Communication',
    favorite: false,
    // subtitle: 'Richard Dawkins',
    badges: ['Recording', 'Business'],
    price: '49.65',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/posters/3.png',
    title: 'Tracing Your Roots Through Food',
    // subtitle: 'Chai Li',
    badges: ['Live', 'Food'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/posters/4.png',
    title: 'Mathematical Thinking',
    // subtitle: 'Kevin Sanjaya',
    badges: ['Offline', 'Science & Tech'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/posters/5.png',
    title: 'Purposeful Communication',
    favorite: false,
    // subtitle: 'Richard Dawkins',
    badges: ['Recording', 'Business'],
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/posters/6.png',
    title: 'Creative Collaboration and Fashion',
    // subtitle: 'Richard Dawkins',
    badges: ['Recording', 'Design & Style'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/posters/7.png',
    title: 'Inclusive Leadership',
    badges: ['Recording', 'Community & Government'],
    favorite: false,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  // {
  //   bgImg: '/media/posters/card-bg (11).jpg',
  //   title: `Runner's Mindset`,
  //   badges: ['Recording', 'Sports & Gaming'],
  //   favorite: false,
  //   price: '49.65',
  //   href: '/class/detail',
  // },
  // {
  //   bgImg: '/media/posters/card-bg (12).jpg',
  //   title: `Bake Like A Pro`,
  //   badges: ['Recording', 'Food'],
  //   favorite: true,
  //   price: '49.65',
  //   href: '/class/detail',
  // },
  // {
  //   bgImg: '/media/posters/card-bg (13).jpg',
  //   title: `Modern Vegetarian Cooking`,
  //   badges: ['Recording', 'Food'],
  //   favorite: true,
  //   price: '49.65',
  //   href: '/class/detail',
  // },
]

export const largeCard: Parameters<typeof Common>[0][] = [
  {
    bgImg: '/media/posters/1.jpg',
    title: 'Developing Entrepreneurial Mindset',
    // subtitle: 'Chai Li',
    badges: ['Live', 'Finance & Accounting'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/posters/2.jpg',
    title: 'Developing Entrepreneurial Mindset',
    // subtitle: 'Kevin Sanjaya',
    badges: ['Offline', 'IT & Software'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/posters/3.jpg',
    title: 'Developing Entrepreneurial Mindset',
    favorite: false,
    // subtitle: 'Richard Dawkins',
    badges: ['Recording', 'Business'],
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/posters/3.png',
    title: 'Developing Entrepreneurial Mindset',
    // subtitle: 'Richard Dawkins',
    badges: ['Recording', 'Health & Fitness'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    title: 'Developing Entrepreneurial Mindset',
    bgImg: '/media/posters/4.png',
    favorite: false,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    badges: ['Recording', 'Business'],
    href: '/class/detail',
  },
  {
    title: 'Developing Entrepreneurial Mindset',
    bgImg: '/media/posters/5.png',
    favorite: false,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    badges: ['Recording', 'Business'],
    href: '/class/detail',
  },
]
