import { Common } from '@Blocks/Card'

export const slimCard: Parameters<typeof Common>[0][] = [
  {
    bgImg: '/media/card-bg (1).jpg',
    title: 'Tracing Your Roots Through Food',
    // subtitle: 'Chai Li',
    badges: ['Live', 'Food'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg (14).jpg',
    title: 'Mathematical Thinking',
    // subtitle: 'Kevin Sanjaya',
    badges: ['Offline', 'Science & Tech'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg (15).jpg',
    title: 'Purposeful Communication',
    favorite: false,
    // subtitle: 'Richard Dawkins',
    badges: ['Recording', 'Business'],
    price: '49.65',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg (4).jpg',
    title: 'Tracing Your Roots Through Food',
    // subtitle: 'Chai Li',
    badges: ['Live', 'Food'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg (5).jpg',
    title: 'Mathematical Thinking',
    // subtitle: 'Kevin Sanjaya',
    badges: ['Offline', 'Science & Tech'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg (6).jpg',
    title: 'Purposeful Communication',
    favorite: false,
    // subtitle: 'Richard Dawkins',
    badges: ['Recording', 'Business'],
    price: '49.65',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg (8).jpg',
    title: 'Creative Collaboration and Fashion',
    // subtitle: 'Richard Dawkins',
    badges: ['Recording', 'Design & Style'],
    favorite: true,
    price: '49.65',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg (10).jpg',
    title: 'Inclusive Leadership',
    badges: ['Recording', 'Community & Government'],
    favorite: false,
    price: '49.65',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg (11).jpg',
    title: `Runner's Mindset`,
    badges: ['Recording', 'Sports & Gaming'],
    favorite: false,
    price: '49.65',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg (12).jpg',
    title: `Bake Like A Pro`,
    badges: ['Recording', 'Food'],
    favorite: true,
    price: '49.65',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg (13).jpg',
    title: `Modern Vegetarian Cooking`,
    badges: ['Recording', 'Food'],
    favorite: true,
    price: '49.65',
    href: '/class/detail',
  },
]

export const largeCard: Parameters<typeof Common>[0][] = [
  {
    bgImg: '/media/card-bg-lg (1).jpg',
    title: 'Developing Entrepreneurial Mindset',
    // subtitle: 'Chai Li',
    badges: ['Live', 'Finance & Accounting'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg-lg (2).jpg',
    title: 'Developing Entrepreneurial Mindset',
    // subtitle: 'Kevin Sanjaya',
    badges: ['Offline', 'IT & Software'],
    favorite: true,
    price: '49.65',
    quota: '8/10',
    date: 'Jan 21-29, 22',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg-lg (3).jpg',
    title: 'Developing Entrepreneurial Mindset',
    favorite: false,
    // subtitle: 'Richard Dawkins',
    badges: ['Recording', 'Business'],
    price: '49.65',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg-lg (4).jpg',
    title: 'Developing Entrepreneurial Mindset',
    // subtitle: 'Richard Dawkins',
    badges: ['Recording', 'Health & Fitness'],
    favorite: true,
    price: '49.65',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg-lg (5).jpg',
    href: '/class/detail',
  },
  {
    bgImg: '/media/card-bg-lg (6).jpg',
    href: '/class/detail',
  },
]
